services:
  devcontainer:
    container_name: ai-test3-devcontainer
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    # コンテナを起動し続けるためのコマンド
    command: sleep infinity
